import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// //import script
// import './../../node_modules/chart.js/dist/chart.umd'

//import CSS file
import "./globals.css";
import contentStyles from '@/app/styles/ContentStyle.module.css'

//import components
import Navbar from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className={contentStyles['body-container']}>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
